# House Price Prediction Project
#### 1. Problem Definition:
- Goal: predict the sales price for each house 
#### 2. Feature Selection
- Choose feature to train (Feature Engineering)
#### 3. Splitting the datasets
- 'Data', dataset
- 'X', data[features]
- 'y': target variable: 'SalePrice'
#### 4. Training Machine Model

In [6]:
import pandas as pd
import numpy as np

In [7]:
data = pd.read_csv('train.csv', index_col = 'Id')
data.head(5)

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
4           70       RL         60.0     9550   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
4          Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                             
1        0      2    2008        WD         Normal     208500  
2        0      5    2007        WD         Normal     181500  
3        0      9    2008        WD         Normal     223500  
4        0      2    2006        WD        Abnorml     140000  
5        0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

In [8]:
data.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'Wo

2. Feature Selection

In [11]:
features = ['LotArea', 'YearBuilt', '1stFlrSF', '2ndFlrSF','FullBath', 'HalfBath', 'TotRmsAbvGrd']

### 3. Splitting Dataset into X and y

In [15]:
X = data[features]
y = data['SalePrice']
X.head()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  HalfBath  TotRmsAbvGrd
Id                                                                          
1      8450       2003       856       854         2         1             8
2      9600       1976      1262         0         2         0             6
3     11250       2001       920       866         2         1             6
4      9550       1915       961       756         1         0             7
5     14260       2000      1145      1053         2         1             9

In [16]:
y.head()

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

#### X, y -> X_train, y_train, X_valid, y_valid

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.8, test_size = 0.2, random_state = 0)
#random_state = 0 để random fix giá trị, chạy mỗi lần không ra kết quả khác nhau

In [26]:
X_train

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  HalfBath  TotRmsAbvGrd
Id                                                                            
619     11694       2007      1828         0         2         0             9
871      6600       1962       894         0         1         0             5
93      13360       1921       964         0         1         0             5
818     13265       2002      1689         0         2         0             7
303     13704       2001      1541         0         2         0             6
...       ...        ...       ...       ...       ...       ...           ...
764      9430       1999      1268      1097         2         1             8
836      9600       1950      1067         0         2         0             4
1217     8930       1978      1318       584         2         0             8
560      3196       2003      1557         0         2         0             7
685     16770       1998      1195       644         2         1             7

[1168 rows x 7 columns]

### 4. Training Machine Model

In [27]:
from sklearn.tree import DecisionTreeRegressor
dt_model = DecisionTreeRegressor(random_state = 1)
#fit_training data 
dt_model.fit(X_train, y_train)


DecisionTreeRegressor(random_state=1)

In [29]:
y_predict = dt_model.predict(X_test.head())

In [30]:
y_predict

array([335000., 145000., 129000., 207500.,  85000.])

In [31]:
pd.DataFrame({'y': y_test.head(), 'y_predict': y_predict})

y  y_predict
Id                    
530  200624   335000.0
492  133000   145000.0
460  110000   129000.0
280  192000   207500.0
656   88000    85000.0

In [35]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
rf_model = RandomForestRegressor(random_state = 1)
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=1)

In [38]:
rf_val_pred = rf_model.predict(X_test.head()) #hàm predict nhận mảng 2 chiều

In [39]:
rf_val_pred

array([272706.  , 141695.18, 122532.5 , 186060.  ,  90493.5 ])

### Predict with a new input

In [41]:
X_test.head()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  HalfBath  TotRmsAbvGrd
Id                                                                           
530    32668       1957      2515         0         3         0             9
492     9490       1941       958       620         1         0             5
460     7015       1950       979       224         1         0             5
280    10005       1977      1156       866         2         1             8
656     1680       1971       525       567         1         1             6

In [43]:
rf_model.predict([[6969,2021,1000,400,4,5,9]])

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([213655.96])

### 5. Model Evaluation